title: "Epigenetics & Computational RNA Biology Laboratory"
description: "Epigenetics & Computational RNA Biology Laboratory | Xi'an Jiaotong University"
url: "https://yanqianglilab.github.io"
baseurl: ""

markdown: kramdown
theme: minima

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

navigation:
  - name: Home
    link: /
  - name: Research
    link: /research/
  - name: People
    link: /people/
  - name: Publications
    link: /publications/
  - name: Software
    link: /software/
  - name: News
    link: /news/
  - name: Join
    link: /join/
  - name: Contact
    link: /contact/
include:
  - _pages
